---
server:
    port: 8081
    address: localhost
---
#默认使用配置
spring:
  profiles:
    active: dev
---
#公共配置与profiles选择无关 mapperLocations指的路径是src/main/resources
mybatis:
  typeAliasesPackage: com.app.model
  mapperLocations: classpath:mapper/*.xml
---
pagehelper:
   helperDialect: mysql
   reasonable: true
   supportMethodsArguments: true
   params: count=countSql
---
redis:
  host:
    - 127.0.0.1
    - 127.0.0.2
  port: 6379
  timeout: 5000
---
#开发配置
spring:
  datasource:
       name: test
       url: jdbc:mysql://rm-uf64zu10w62yb01t5o.mysql.rds.aliyuncs.com:3306/home
       username: root
       password: Wdj@19910702
       # \u4F7F\u7528druid\u6570\u636E\u6E90
       type: com.alibaba.druid.pool.DruidDataSource
       driver-class-name: com.mysql.jdbc.Driver
       filters: stat
       maxActive: 20
       initialSize: 1
       maxWait: 60000
       minIdle: 1
       timeBetweenEvictionRunsMillis: 60000
       minEvictableIdleTimeMillis: 300000
       validationQuery: select 'x'
       testWhileIdle: true
       testOnBorrow: false
       testOnReturn: false
       poolPreparedStatements: true
       maxOpenPreparedStatements: 20
---
share:
  url: http://nufm.dfcfw.com/EM_Finance2014NumericApplication/JS.aspx?type=CT&cmd=C._A&sty=FCOIATA&sortType=(Code)&sortRule=1&page=1&pageSize=1000000000&js=var%2520VnODumYu=%257Brank:[(x)],pages:(pc),total:(tot)%257D&token=7bc05d0d4c3c22ef9fca8c2a912d779c&jsName=quote_123&_g=0.628606915911589&_=1517561168627
  code:
    - 600022
    - 601001
  mailAddressTO:
    - wangdongjiang@aiyun.com
    - moxiaoyang@baofu.com
---
email:
  sendUserName: wangdongjiang@aliyun.com
  sendUserPwd: Wdj&19910702
  emailHost: smtp.aliyun.com
  emailAuth: true